variable "OS_AUTH_URL" {}
variable "OS_PASSWORD" {}
variable "OS_REGION_NAME" {}
variable "OS_TENANT_NAME" {}
variable "OS_USERNAME" {}
variable "OS_KEYPAIR" {}
variable "OPENSTACK_PROVIDER_NET" {}
variable "OPENSTACK_PRIVATE_NET" {}
variable "OPENSTACK_FLOATING_IP" {}
variable "OPENSTACK_CLOUD" {}
variable VSPHERE_USER  {}
variable VSPHERE_PASSWORD  {}
variable VSPHERE_SERVER  {}
variable VSPHERE_DATACENTER  {}
variable VSPHERE_DATASTORE  {}
variable VSPHERE_RESOURCE_POOL  {}
variable VSPHERE_NETWORK  {}
variable VSPHERE_FOLDER {}
variable VSPHERE_CLUSTER {}